apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: computex-fullstack
spec:
  project: default
  source:
    repoURL: https://github.com/soundn/GitOps-Fullstack-jenkins-pipeline.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
